controller_manager:
  update_rate: 100

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel"]   
    right_wheel_names: ["right_wheel"]  

    wheel_separation: 0.45              
    wheel_radius: 0.1                 
    odom_frame_id: "odom"              
    base_frame_id: "base_link"        
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001] 
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    publish_rate: 50.0                  
    cmd_vel_timeout: 0.5              

    enable_odom_tf: true              
    open_loop: false                   
    velocity_rolling_window_size: 10   

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0              
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 0.5         
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5               
        min_velocity: -1.5
        has_acceleration_limits: true
        max_acceleration: 0.8           
        has_jerk_limits: false
